-- Ensure users table has fields required by current User entity
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS streak integer;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS total_points bigint;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS theme_preference varchar(255);

UPDATE users SET streak = 0 WHERE streak IS NULL;
UPDATE users SET total_points = 0 WHERE total_points IS NULL;
UPDATE users
SET theme_preference = 'SYSTEM'
WHERE theme_preference IS NULL
   OR theme_preference NOT IN ('LIGHT','DARK','SYSTEM');

ALTER TABLE IF EXISTS users ALTER COLUMN streak SET DEFAULT 0;
ALTER TABLE IF EXISTS users ALTER COLUMN total_points SET DEFAULT 0;
ALTER TABLE IF EXISTS users ALTER COLUMN theme_preference SET DEFAULT 'SYSTEM';

ALTER TABLE IF EXISTS users ALTER COLUMN streak SET NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN total_points SET NOT NULL;
ALTER TABLE IF EXISTS users ALTER COLUMN theme_preference SET NOT NULL;

ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS users_theme_preference_check;
ALTER TABLE IF EXISTS users
    ADD CONSTRAINT users_theme_preference_check
    CHECK (theme_preference IN ('LIGHT','DARK','SYSTEM'));
ALTER TABLE user_challenges DROP CONSTRAINT IF EXISTS user_challenges_status_check;
ALTER TABLE user_challenges ADD CONSTRAINT user_challenges_status_check CHECK (status IN ('ASSIGNED','COMPLETED'));
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Hidden Cafe Discovery', 'Find a quiet cafe you have never visited and spend 30 minutes there reading or people-watching.', 'EXPLORE_CITY', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Hidden Cafe Discovery' AND description = 'Find a quiet cafe you have never visited and spend 30 minutes there reading or people-watching.' AND category = 'EXPLORE_CITY' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Street Art Snapshot', 'Walk one street you rarely take and photograph 3 pieces of street art or murals.', 'EXPLORE_CITY', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Street Art Snapshot' AND description = 'Walk one street you rarely take and photograph 3 pieces of street art or murals.' AND category = 'EXPLORE_CITY' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Park Bench Pause', 'Visit a nearby park you do not usually go to and sit for 20 minutes observing the area.', 'EXPLORE_CITY', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Park Bench Pause' AND description = 'Visit a nearby park you do not usually go to and sit for 20 minutes observing the area.' AND category = 'EXPLORE_CITY' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Market Mystery Tour', 'Visit a local market and try one food item you have never tasted.', 'EXPLORE_CITY', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Market Mystery Tour' AND description = 'Visit a local market and try one food item you have never tasted.' AND category = 'EXPLORE_CITY' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Historic Block Fact Walk', 'Pick a historic building, walk there, and learn one fact from a plaque or a quick search.', 'EXPLORE_CITY', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Historic Block Fact Walk' AND description = 'Pick a historic building, walk there, and learn one fact from a plaque or a quick search.' AND category = 'EXPLORE_CITY' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Spice Aisle Hunt', 'Go to a grocery store and find three Indian spices or ingredients you have not used before.', 'EXPLORE_CITY', 'MEDIUM', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Spice Aisle Hunt' AND description = 'Go to a grocery store and find three Indian spices or ingredients you have not used before.' AND category = 'EXPLORE_CITY' AND energy_level = 'MEDIUM' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Transit Adventure', 'Take a bus or train line you have never used and explore the final stop for at least 1 hour.', 'EXPLORE_CITY', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Transit Adventure' AND description = 'Take a bus or train line you have never used and explore the final stop for at least 1 hour.' AND category = 'EXPLORE_CITY' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Rangoli Pattern Walk', 'Walk around campus or your city and photograph 5 colorful geometric patterns inspired by rangoli.', 'EXPLORE_CITY', 'HIGH', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Rangoli Pattern Walk' AND description = 'Walk around campus or your city and photograph 5 colorful geometric patterns inspired by rangoli.' AND category = 'EXPLORE_CITY' AND energy_level = 'HIGH' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'City Square Loop', 'Do a 30-minute loop around your city center or main plaza, inspired by Russian city squares, and note three landmarks.', 'EXPLORE_CITY', 'HIGH', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'City Square Loop' AND description = 'Do a 30-minute loop around your city center or main plaza, inspired by Russian city squares, and note three landmarks.' AND category = 'EXPLORE_CITY' AND energy_level = 'HIGH' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Geometry Architecture Walk', 'Take a long walk and photograph 5 bold geometric building features inspired by constructivist design.', 'EXPLORE_CITY', 'HIGH', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Geometry Architecture Walk' AND description = 'Take a long walk and photograph 5 bold geometric building features inspired by constructivist design.' AND category = 'EXPLORE_CITY' AND energy_level = 'HIGH' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Trend Research Hour', 'Spend an hour exploring a current student trend you do not understand and learn what people enjoy about it.', 'TREND_BASED', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Trend Research Hour' AND description = 'Spend an hour exploring a current student trend you do not understand and learn what people enjoy about it.' AND category = 'TREND_BASED' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Meme Museum', 'Collect five campus memes or inside jokes and explain each one to yourself or a friend.', 'TREND_BASED', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Meme Museum' AND description = 'Collect five campus memes or inside jokes and explain each one to yourself or a friend.' AND category = 'TREND_BASED' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Chai Craze Check', 'Make or order a masala chai and see why it is a campus favorite.', 'TREND_BASED', 'LOW', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Chai Craze Check' AND description = 'Make or order a masala chai and see why it is a campus favorite.' AND category = 'TREND_BASED' AND energy_level = 'LOW' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Trend Snapshot', 'Find three examples of a current Russian youth trend in music, fashion, or slang.', 'TREND_BASED', 'LOW', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Trend Snapshot' AND description = 'Find three examples of a current Russian youth trend in music, fashion, or slang.' AND category = 'TREND_BASED' AND energy_level = 'LOW' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Micro-Trend Experiment', 'Try one current campus micro-trend for a day, such as a study method, outfit, or snack.', 'TREND_BASED', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Micro-Trend Experiment' AND description = 'Try one current campus micro-trend for a day, such as a study method, outfit, or snack.' AND category = 'TREND_BASED' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Trend Time Capsule', 'Create a small trend board with five current styles or ideas and save it to revisit later.', 'TREND_BASED', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Trend Time Capsule' AND description = 'Create a small trend board with five current styles or ideas and save it to revisit later.' AND category = 'TREND_BASED' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Playlist Today', 'Create a playlist of six songs currently popular in Russia and listen on a walk.', 'TREND_BASED', 'MEDIUM', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Playlist Today' AND description = 'Create a playlist of six songs currently popular in Russia and listen on a walk.' AND category = 'TREND_BASED' AND energy_level = 'MEDIUM' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Trend Remix Project', 'Create a small project inspired by a current trend, such as a poster, playlist, or outfit.', 'TREND_BASED', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Trend Remix Project' AND description = 'Create a small project inspired by a current trend, such as a poster, playlist, or outfit.' AND category = 'TREND_BASED' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Pop-up Trend Night', 'Host or join a mini gathering to try a trend together, like a board-game night or a new snack.', 'TREND_BASED', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Pop-up Trend Night' AND description = 'Host or join a mini gathering to try a trend together, like a board-game night or a new snack.' AND category = 'TREND_BASED' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Dance Step Challenge', 'Learn a short dance step popular on Indian campuses and teach it to a friend or record it for yourself.', 'TREND_BASED', 'HIGH', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Dance Step Challenge' AND description = 'Learn a short dance step popular on Indian campuses and teach it to a friend or record it for yourself.' AND category = 'TREND_BASED' AND energy_level = 'HIGH' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Library Corner Discovery', 'Find a corner of the library you have never used and spend 45 minutes there studying or relaxing.', 'CAMPUS_LIFE', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Library Corner Discovery' AND description = 'Find a corner of the library you have never used and spend 45 minutes there studying or relaxing.' AND category = 'CAMPUS_LIFE' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Green Space Pause', 'Visit a quiet green spot on campus and take a 20-minute break there.', 'CAMPUS_LIFE', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Green Space Pause' AND description = 'Visit a quiet green spot on campus and take a 20-minute break there.' AND category = 'CAMPUS_LIFE' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Chai Study Break', 'Invite a classmate for a short chai break between study sessions.', 'CAMPUS_LIFE', 'LOW', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Chai Study Break' AND description = 'Invite a classmate for a short chai break between study sessions.' AND category = 'CAMPUS_LIFE' AND energy_level = 'LOW' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Department Tour', 'Visit a department building you have never entered and find one interesting display or lab.', 'CAMPUS_LIFE', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Department Tour' AND description = 'Visit a department building you have never entered and find one interesting display or lab.' AND category = 'CAMPUS_LIFE' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Event Attendance', 'Attend a campus event you would not normally go to and stay for at least 30 minutes.', 'CAMPUS_LIFE', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Event Attendance' AND description = 'Attend a campus event you would not normally go to and stay for at least 30 minutes.' AND category = 'CAMPUS_LIFE' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Study Spot Roulette', 'Study in three different campus locations today and pick a favorite.', 'CAMPUS_LIFE', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Study Spot Roulette' AND description = 'Study in three different campus locations today and pick a favorite.' AND category = 'CAMPUS_LIFE' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Tea Room Meetup', 'Set up a simple tea break in a common room inspired by Russian student hangouts and invite someone to join.', 'CAMPUS_LIFE', 'MEDIUM', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Tea Room Meetup' AND description = 'Set up a simple tea break in a common room inspired by Russian student hangouts and invite someone to join.' AND category = 'CAMPUS_LIFE' AND energy_level = 'MEDIUM' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Architecture Hunt', 'Photograph the most interesting architectural features of 10 different campus buildings.', 'CAMPUS_LIFE', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Architecture Hunt' AND description = 'Photograph the most interesting architectural features of 10 different campus buildings.' AND category = 'CAMPUS_LIFE' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Kruzhok Tryout', 'Attend a student club meeting and participate for at least 30 minutes, kruzhok-style.', 'CAMPUS_LIFE', 'HIGH', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Kruzhok Tryout' AND description = 'Attend a student club meeting and participate for at least 30 minutes, kruzhok-style.' AND category = 'CAMPUS_LIFE' AND energy_level = 'HIGH' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Campus Fest Crew', 'Help prepare for a campus cultural event or decorate a shared space for one hour.', 'CAMPUS_LIFE', 'HIGH', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Campus Fest Crew' AND description = 'Help prepare for a campus cultural event or decorate a shared space for one hour.' AND category = 'CAMPUS_LIFE' AND energy_level = 'HIGH' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Compliment Stranger', 'Give a genuine compliment to someone you do not know well, in person or online.', 'SOCIAL_SPARK', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Compliment Stranger' AND description = 'Give a genuine compliment to someone you do not know well, in person or online.' AND category = 'SOCIAL_SPARK' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Message an Old Friend', 'Reach out to someone you have not spoken to in six months and say hello.', 'SOCIAL_SPARK', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Message an Old Friend' AND description = 'Reach out to someone you have not spoken to in six months and say hello.' AND category = 'SOCIAL_SPARK' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Chai Connection', 'Invite someone for a low-key chai break and keep it casual.', 'SOCIAL_SPARK', 'LOW', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Chai Connection' AND description = 'Invite someone for a low-key chai break and keep it casual.' AND category = 'SOCIAL_SPARK' AND energy_level = 'LOW' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Conversation Deep Dive', 'Have a 15-minute conversation where you focus only on asking the other person questions.', 'SOCIAL_SPARK', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Conversation Deep Dive' AND description = 'Have a 15-minute conversation where you focus only on asking the other person questions.' AND category = 'SOCIAL_SPARK' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Group Study Session', 'Organize a small study session with two to four people.', 'SOCIAL_SPARK', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Group Study Session' AND description = 'Organize a small study session with two to four people.' AND category = 'SOCIAL_SPARK' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Tea Walk Invite', 'Invite someone for a short walk with hot tea, a relaxed Russian-style catch-up.', 'SOCIAL_SPARK', 'MEDIUM', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Tea Walk Invite' AND description = 'Invite someone for a short walk with hot tea, a relaxed Russian-style catch-up.' AND category = 'SOCIAL_SPARK' AND energy_level = 'MEDIUM' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Community Event Hosting', 'Host a small event like a movie night, potluck, or game night for at least five people.', 'SOCIAL_SPARK', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Community Event Hosting' AND description = 'Host a small event like a movie night, potluck, or game night for at least five people.' AND category = 'SOCIAL_SPARK' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Game Night Organizer', 'Organize a casual game night and bring together at least two friend groups.', 'SOCIAL_SPARK', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Game Night Organizer' AND description = 'Organize a casual game night and bring together at least two friend groups.' AND category = 'SOCIAL_SPARK' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Volunteer Together', 'Gather a few friends to do a small volunteer activity or campus cleanup.', 'SOCIAL_SPARK', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Volunteer Together' AND description = 'Gather a few friends to do a small volunteer activity or campus cleanup.' AND category = 'SOCIAL_SPARK' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Social Circle Mashup', 'Introduce two friends who do not know each other and start a short group conversation.', 'SOCIAL_SPARK', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Social Circle Mashup' AND description = 'Introduce two friends who do not know each other and start a short group conversation.' AND category = 'SOCIAL_SPARK' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Foreign Language Film', 'Watch a film in a language you do not speak with subtitles.', 'CULTURAL_EXCHANGE', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Foreign Language Film' AND description = 'Watch a film in a language you do not speak with subtitles.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'International Music Discovery', 'Create a playlist of 10 songs from 10 different countries you have not explored.', 'CULTURAL_EXCHANGE', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'International Music Discovery' AND description = 'Create a playlist of 10 songs from 10 different countries you have not explored.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'India Festival Snapshot', 'Learn about one Indian festival outside your region and watch a short video of it.', 'CULTURAL_EXCHANGE', 'LOW', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'India Festival Snapshot' AND description = 'Learn about one Indian festival outside your region and watch a short video of it.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'LOW' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Tea Ritual', 'Brew a cup of tea and read about a Russian tea tradition while you drink it.', 'CULTURAL_EXCHANGE', 'LOW', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Tea Ritual' AND description = 'Brew a cup of tea and read about a Russian tea tradition while you drink it.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'LOW' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Global Recipe Attempt', 'Cook a simple dish from a culture different from your own and share it with someone.', 'CULTURAL_EXCHANGE', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Global Recipe Attempt' AND description = 'Cook a simple dish from a culture different from your own and share it with someone.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Regional Indian Dish', 'Try cooking a simple Indian regional dish you have never made before.', 'CULTURAL_EXCHANGE', 'MEDIUM', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Regional Indian Dish' AND description = 'Try cooking a simple Indian regional dish you have never made before.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'MEDIUM' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Market Item', 'Try a Russian or Eastern European snack from a store or an easy recipe.', 'CULTURAL_EXCHANGE', 'MEDIUM', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Market Item' AND description = 'Try a Russian or Eastern European snack from a store or an easy recipe.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'MEDIUM' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'International Student Connection', 'Have a meaningful conversation with someone from a different country about daily life and culture.', 'CULTURAL_EXCHANGE', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'International Student Connection' AND description = 'Have a meaningful conversation with someone from a different country about daily life and culture.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Indian Culture Share Night', 'Host a small Indian culture share with music, a snack, or a story for two or more friends.', 'CULTURAL_EXCHANGE', 'HIGH', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Indian Culture Share Night' AND description = 'Host a small Indian culture share with music, a snack, or a story for two or more friends.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'HIGH' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Culture Night', 'Host a small Russian culture share with music, a film clip, or tea for two or more friends.', 'CULTURAL_EXCHANGE', 'HIGH', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Culture Night' AND description = 'Host a small Russian culture share with music, a film clip, or tea for two or more friends.' AND category = 'CULTURAL_EXCHANGE' AND energy_level = 'HIGH' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Digital Cleanup', 'Delete 50 unused photos or files and organize one folder on your phone or laptop.', 'WILDCARD', 'LOW', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Digital Cleanup' AND description = 'Delete 50 unused photos or files and organize one folder on your phone or laptop.' AND category = 'WILDCARD' AND energy_level = 'LOW' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Yoga Reset', 'Do a gentle 10-minute yoga stretch to reset your day.', 'WILDCARD', 'LOW', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Yoga Reset' AND description = 'Do a gentle 10-minute yoga stretch to reset your day.' AND category = 'WILDCARD' AND energy_level = 'LOW' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Russian Word Labels', 'Learn five simple Russian words and label five items in your room with sticky notes.', 'WILDCARD', 'LOW', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Russian Word Labels' AND description = 'Learn five simple Russian words and label five items in your room with sticky notes.' AND category = 'WILDCARD' AND energy_level = 'LOW' AND culture = 'RUSSIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Skill Hour', 'Spend one hour learning something new using a tutorial or course.', 'WILDCARD', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Skill Hour' AND description = 'Spend one hour learning something new using a tutorial or course.' AND category = 'WILDCARD' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Analog Evening', 'For one evening, avoid digital entertainment and do something offline.', 'WILDCARD', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Analog Evening' AND description = 'For one evening, avoid digital entertainment and do something offline.' AND category = 'WILDCARD' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Creative Expression', 'Create something small like a drawing, poem, or craft with no pressure to perfect it.', 'WILDCARD', 'MEDIUM', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Creative Expression' AND description = 'Create something small like a drawing, poem, or craft with no pressure to perfect it.' AND category = 'WILDCARD' AND energy_level = 'MEDIUM' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Spice Mix Experiment', 'Make a simple Indian spice mix or snack and try it with a friend.', 'WILDCARD', 'MEDIUM', true, 'INDIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Spice Mix Experiment' AND description = 'Make a simple Indian spice mix or snack and try it with a friend.' AND category = 'WILDCARD' AND energy_level = 'MEDIUM' AND culture = 'INDIA');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Random Act of Kindness Day', 'Do five small acts of kindness for five different people in one day.', 'WILDCARD', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Random Act of Kindness Day' AND description = 'Do five small acts of kindness for five different people in one day.' AND category = 'WILDCARD' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT '24-Hour Creative Challenge', 'Complete a small creative project within 24 hours, like a short story or photo series.', 'WILDCARD', 'HIGH', true, 'GLOBAL' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = '24-Hour Creative Challenge' AND description = 'Complete a small creative project within 24 hours, like a short story or photo series.' AND category = 'WILDCARD' AND energy_level = 'HIGH' AND culture = 'GLOBAL');
INSERT INTO challenges (title, description, category, energy_level, active, culture) SELECT 'Cozy Tea Game Night', 'Host a cozy tea-and-cards night inspired by Russian gatherings and invite a few friends.', 'WILDCARD', 'HIGH', true, 'RUSSIA' WHERE NOT EXISTS (SELECT 1 FROM challenges WHERE title = 'Cozy Tea Game Night' AND description = 'Host a cozy tea-and-cards night inspired by Russian gatherings and invite a few friends.' AND category = 'WILDCARD' AND energy_level = 'HIGH' AND culture = 'RUSSIA');

